name: Check LaTeX Formatting

on: [pull_request]

jobs:
  latexindent:
    runs-on: ubuntu-latest
    container:
      image: cmhughes/latexindent.pl:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Formatting
        run: |
          # Find all tex files and run latexindent in check mode
          # -s: silent mode
          # -c: check mode (exit code 1 if file changes)
          find . -name "*.tex" -not -path "./.git/*" -print0 | xargs -0 latexindent -s -c
